package com.afsoltech.kops.core.model.integration

enum class PaymentStatus {
    DRAFT, ALL, IN_PROGRESS, COMPLETED, NUMBER_EXISTS, FAILED, CANCEL, ALREADY_PAID, CANCELED_NOTICE, NOTICE_NUMBER_ERROR, TAXPAYER_ERROR,
    AMOUNT_ERROR, SYSTEM_ERROR, UNKNOWN_ERROR, NO_LIST
}