package com.afsoltech.kops.core.model.attribute

enum class ErrorCode {
    INTERNAL_ERROR,
    INVALID_DATA_ERROR,
    MISSING_DATA_ERROR,
    DATABASE_ERROR,
    NETWORK_ERROR,
    DUPLICATE_TRANSACTION_ID,
    RETRY_LIMIT_EXCEEDED,
    OUTBOUND_PARTICIPANT_NOT_SUPPORTED,
    OUTBOUND_PARTICIPANT_INTEGRATION_DOWN,
    OUTBOUND_PARTICIPANT_INTERNAL_ERROR,
    OUTBOUND_PARTICIPANT_NOT_REACHABLE,
    OUTBOUND_PARTICIPANT_REQUEST_TIMEOUT,
    OUTBOUND_PARTICIPANT_NO_RESPONSE
}